services:

  discovery-service:
    build:
      context: .
    container_name: discovery-service

    ports:
      - "8761:8761"

    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
